/* ------------------------------------------------------- */
/* Nombres aleatorios                                      */
/* ------------------------------------------------------- */
var namePool = [
  "Nehin", "Sukiw",	"Esstan",	"Sirothrod", "Yeror", "Lyryn",	"Turiass", "Galam",
  "Ormmor", "Ser'os",	"Hintas",	"Math", "Rentis",	"Atem",	"Ach'en",	"Nysight",
  "Oughdel", "Athingwor",	"Sayskel", "Inas", "Warton",	"Taiel", "Achad",	"Tia'que",
  "Nicad", "Erage",	"Queash",	"Iyoz", "Tianight",	"Lieb",	"Rayeos",	"Ir'tiau",
  "Polche",	"Norwar",	"Reilder", "Oughlyeat", "Ueta",	"Onard", "Aldeng", "Ang'nysa",
  "Redaso",	"Kimcer",	"Sileraw", "Eml", "Risang",	"Rislerche", "Hatwar",	"Raywarund",
  "Poldan",	"Quaia",	"Bador", "Chaleo","Whad",	"Zhupol",	"Urnengran", "Raywor",
  "Phagh", "Hat-omeg", "Veawight","Echgarroth", "Ossay", "Rados",	"Athem", "Tinelm",
  "Isach", "Kalryn", "Hisely", "Phylcha-tia", "Ribanwor",	"Hin'honu",	"Peritia", "Delb",
  "Ild'yer", "Osac", "Smytas", "Uskos", "Tyloni",	"Iss'osi", "Lyesul", "Cerril",
  "Gar'or",	"Ziriry",	"Sayage",	"Warim", "Bagib", "Rudra",	"Elmhat",	"Ehatu",
  "Y'enthden", "Delvor", "Orine",	"Ashskin", "Anightim",	"Delcris", "Hinbom", "Kimxine",
  "Bansam",	"Ina'eld", "Honskele", "Tanch",
  "Ustech",	"Ivesacki",	"Uskhone", "Zheentcer",
  "Say'eti", "Eris",	"Eross", "Maroco",
  "Sould", "Gysab", "Snat", "Emgh",
  "Tintor", "Sulild", "Ingmor", "Urntor",
  "Hinost", "Etyer", "Istas", "Eesso",
  "Ustskel", "Dinal", "Torrisa", "Oighta",
  "Deremy", "Enque", "Libiv", "Olddbel",
  "Age'taio", "Ech'old", "Ildnal", "Delathi",
  "Lyden", "Ildack", "Ray'rana", "Dra'iss",
  "Moriss", "Nucoju", "Delir", "Serdynper",
  "Ranaurn", "Zior", "Ler'cha'euk", "Onkel",
  "Niachusk", "Antoor", "Lyeurn", "Reakche",
  "Oseri", "Yacyno", "Cheiph", "Morlerkin",
  "Adb", "Usevo", "Chreyntche", "Emn",
  "Laihan", "Risyad", "Bandel", "Shycer",
  "Rilraku", "Nysang", "Unt'che", "Alevor",
  "Skel'enth", "Cotola", "Keegtan", "Nomoj",
  "Smytheress", "Oumy", "Theron", "Chaus",
  "Orant'lt", "Ightest", "Umashale", "Enhincer",
  "Che'um", "Ukimo", "Per'ess", "Staiyang",
  "Ildeld", "Ia'aso", "Turetrod", "Mor'hona",
  "Nakim", "Asoch", "Chemorden", "Boer",
  "Buyuro", "Solic", "Ormden", "Theissusk",
  "Limina", "Roriy", "Urnrada", "Tiagha",
  "Dratai", "Emet", "Tasatque", "Dar'os",
  "Worisash", "Becar", "Livix", "Oseni",
  "Kalque", "Elm'dena", "Ormhin", "Thert",
  "Yeynt", "Etim", "Ightorcer", "Aughst",
  "Omhin", "Drayer", "Samndar", "Delold",
  "Dynst", "Chadale", "Awdbel", "Ageachild",
  "Zhuik", "Issusk", "Ryend", "Lyardild",
  "Enrisden", "Samding", "Ineran", "Omsul",
  "Kal'ormy", "Tororm", "Tezylo", "Zeedny",
  "Lorend", "Wovar", "Per'as", "Dalemese",
  "Vesceru", "Kelrad", "Chrodechild", "Hang-on",
  "Skjörn", "Akestu", "Tuliëlle", "Worver",
  "Rumina", "Blessin", "Eva", "Lucita"
];
